### ISSUE TITLE
Backbone dependency change

### ISSUE THREAD

**Issue by mnoack** [launchscout/backtastic#6]
Hi, On our fork we've made a change to switch from rails-backbone to backbone-on-rails. It seems to be a seamless change and the benefits are backbone-on-rails is regularly updated (we needed the latest backbone to fix some bugs) without causing our app any issues.

https://github.com/sealink/backtastic/commit/96c6c48f9d93952484b105bc02bc312d0bd0545b

Also we have other commits which might be of interest for you, or alternately I could help you maintain this project and merge our commits in.

**Comment by superchris** [comment]
Hi Michael,

Can you submit a pull request for this? I'm not actively working on this project, as I'm doing most of my work in angular these days, but I'll be happy to merge PRs.

**Comment by mnoack** [comment]
Hi @superchris I've submitted 3 PR's for the various improvements I've done to backtastic.

It includes the one this issue discussed, also one to add new helpers, and one that standardises existing helpers the 'rails way' (admittedly backwards incompatible so I don't know how you'll feel about that one)

**Comment by mnoack** [comment]
Hi @superchris - Sorry to be a pain but could you check on those 3 PR's, or at least the 2 non-backwards compatible ones :)

Thank You

**Comment by mnoack** [comment]
Hi @superchris if you want I'm happy to be added as a committer to this repo so I can help you with this and other PR's

**Comment by superchris** [comment]
Michael, sorry to be so slow getting to this. I've merged your PRs and will go ahead and add you as a committer
